#!/bin/sh
# Relaunch with the project virtualenv so `./read_guardian.py` works directly.
""":"
exec "$(dirname "$0")/.venv/bin/python" "$0" "$@"
":"""
"""Print every library value when the monitor sends a new reading.

Each line is the expression a script can copy:

    reading.ph                     6.20
    reading.fahrenheit             69.62 F
    reading.conductivity("CF")     0.00
"""

import sys

from bluelab import Guardian, GuardianError


def format_reading(reading):
    """Return one block that calls every public value on a reading."""
    rows = [
        ("reading.ph", f"{reading.ph:.2f}"),
        ("reading.ph_mv", f"{reading.ph_mv:.1f} mV"),
        ("reading.celsius", f"{reading.celsius:.2f} C"),
        ('reading.temperature("C")', f"{reading.temperature('C'):.2f} C"),
        ("reading.fahrenheit", f"{reading.fahrenheit:.2f} F"),
        ('reading.temperature("F")', f"{reading.temperature('F'):.2f} F"),
        ("reading.temperature_c", f"{reading.temperature_c:.2f} C"),
        ("reading.ec", f"{reading.ec:.2f}"),
        ('reading.conductivity("EC")', f"{reading.conductivity('EC'):.2f}"),
        ("reading.cf", f"{reading.cf:.2f}"),
        ('reading.conductivity("CF")', f"{reading.conductivity('CF'):.2f}"),
        ("reading.ppm_500", f"{reading.ppm_500:.0f} ppm"),
        ('reading.conductivity("ppm500")', f"{reading.conductivity('ppm500'):.0f} ppm"),
        ("reading.ppm_700", f"{reading.ppm_700:.0f} ppm"),
        ('reading.conductivity("ppm700")', f"{reading.conductivity('ppm700'):.0f} ppm"),
        ("reading.status", reading.status),
        ("reading.ec_flag", reading.ec_flag),
        ("reading.temp_flag", reading.temp_flag),
        ("reading.ph_flag", reading.ph_flag),
        ("reading.tick", str(reading.tick)),
        ("reading.raw_a", reading.raw_a),
        ("reading.raw_b", reading.raw_b),
        ("str(reading)", str(reading)),
    ]
    width = max(len(label) for label, _ in rows)
    stamp = reading.received_at.strftime("%H:%M:%S")
    lines = [stamp]
    lines.extend(f"  {label:<{width}}  {value}" for label, value in rows)
    return "\n".join(lines)


def main():
    port = sys.argv[1] if len(sys.argv) > 1 else None
    try:
        monitor = Guardian(port)
    except GuardianError as exc:
        sys.exit(str(exc))

    print(f"Reading {monitor.port} at {monitor.baud} baud.", flush=True)
    print("Press Ctrl+C to stop.", flush=True)
    try:
        with monitor:
            for reading in monitor:
                print(format_reading(reading), flush=True)
                print(flush=True)
    except KeyboardInterrupt:
        print(flush=True)


if __name__ == "__main__":
    main()

# This script was generated by an AI. Confirm the wiring with a multimeter.
